type User {
  username: String! @unique
  email: String! @unique
  avatar: String!
  password: String
  createdAt: Date!
  googleId: ID @unique
  surveys: [Survey]
}

type Option {
  name: String!
  other: String
  createdAt: Date!
  questionId: Question!
}

type Question {
  title: String!
  isOption: Boolean!
  isField: Boolean!
  options: [Option]
  fieldPlaceholder: String
  createdAt: Date!
  surveyId: Survey!
}

type Survey {
  slug: String! @unique
  title: String!
  description: String!
  createdAt: Date!
  questions: [Question!]!
  creator: User!
}

type Query {
  getSurvey(slug: String!): Survey
  loginWithGoogle(googleId: ID!): User
  loginWithCredentials(username: String!, password: String!): User
}
